// HorizonAI Service Layer
// This layer abstracts API calls for future backend integration
// Currently uses mock data - will be replaced with real API calls

import { mockModels, mockPlans, mockConversations, mockUsageStats, suggestedPrompts, faqData } from '../data/mockData';
import type { Model, Plan, Conversation, Message, UsageStats, User } from '../types';
import { generateId } from '../utils/helpers';

// Simulated delay for realistic loading states
const simulateDelay = (ms: number = 500) => new Promise(resolve => setTimeout(resolve, ms));

// ============ Auth Service ============
export const authService = {
  async login(_email: string, _password: string): Promise<{ user: User; token: string }> {
    await simulateDelay(1000);
    
    // Demo validation
    if (!_email || !_password) {
      throw new Error('Email and password are required');
    }
    
    // Mock successful login
    const user: User = {
      id: 'user-1',
      name: 'Demo User',
      email: _email,
      plan: 'free',
      createdAt: new Date(),
    };
    
    return { user, token: 'mock-jwt-token' };
  },

  async signup(name: string, email: string, password: string): Promise<{ user: User; token: string }> {
    await simulateDelay(1000);
    
    if (!name || !email || !password) {
      throw new Error('All fields are required');
    }
    
    const user: User = {
      id: generateId(),
      name,
      email,
      plan: 'free',
      createdAt: new Date(),
    };
    
    return { user, token: 'mock-jwt-token' };
  },

  async logout(): Promise<void> {
    await simulateDelay(300);
  },

  async forgotPassword(_email: string): Promise<void> {
    await simulateDelay(1000);
  },

  async getCurrentUser(): Promise<User | null> {
    await simulateDelay(300);
    // Return null for now - no auth implemented
    return null;
  },
};

// ============ Models Service ============
export const modelsService = {
  async getAllModels(): Promise<Model[]> {
    await simulateDelay(300);
    return mockModels;
  },

  async getModelById(id: string): Promise<Model | undefined> {
    await simulateDelay(200);
    return mockModels.find(m => m.id === id);
  },

  async getAvailableModels(userPlan: string): Promise<Model[]> {
    await simulateDelay(300);
    return mockModels.filter(m => {
      if (userPlan === 'premium2') return true;
      if (userPlan === 'premium1') return m.tier !== 'premium2';
      return m.tier === 'free';
    });
  },
};

// ============ Chat Service ============
export const chatService = {
  async getConversations(): Promise<Conversation[]> {
    await simulateDelay(500);
    return mockConversations;
  },

  async getConversation(id: string): Promise<Conversation | undefined> {
    await simulateDelay(300);
    return mockConversations.find(c => c.id === id);
  },

  async createConversation(title: string): Promise<Conversation> {
    await simulateDelay(300);
    const newConversation: Conversation = {
      id: generateId(),
      title,
      messages: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    };
    return newConversation;
  },

  async sendMessage(_conversationId: string, message: Message): Promise<Message> {
    await simulateDelay(1000);
    // Mock response - in production, this would call the AI API
    const response: Message = {
      id: generateId(),
      role: 'assistant',
      content: "This is a demo response. In the production version, this will be generated by the selected AI model.\n\nYour message was: " + message.content,
      timestamp: new Date(),
      model: message.model || 'horizon-auto',
    };
    return response;
  },

  async deleteConversation(_id: string): Promise<void> {
    await simulateDelay(300);
  },

  async updateConversation(id: string, updates: Partial<Conversation>): Promise<Conversation> {
    await simulateDelay(300);
    const conversation = mockConversations.find(c => c.id === id);
    if (!conversation) throw new Error('Conversation not found');
    return { ...conversation, ...updates };
  },
};

// ============ Usage Service ============
export const usageService = {
  async getUsageStats(): Promise<UsageStats> {
    await simulateDelay(300);
    return mockUsageStats;
  },

  async resetUsage(): Promise<void> {
    await simulateDelay(500);
  },
};

// ============ Plans Service ============
export const plansService = {
  async getPlans(): Promise<Plan[]> {
    await simulateDelay(300);
    return mockPlans;
  },

  async getPlanById(id: string): Promise<Plan | undefined> {
    await simulateDelay(200);
    return mockPlans.find(p => p.id === id);
  },

  async upgradePlan(_planId: string): Promise<void> {
    await simulateDelay(1000);
    // In production, this would initiate the payment flow
  },
};

// ============ User Service ============
export const userService = {
  async getProfile(): Promise<User> {
    await simulateDelay(300);
    return {
      id: 'user-1',
      name: 'Demo User',
      email: 'demo@horizonai.com',
      plan: 'free',
      createdAt: new Date('2024-01-01'),
    };
  },

  async updateProfile(updates: Partial<User>): Promise<User> {
    await simulateDelay(500);
    return {
      id: 'user-1',
      name: updates.name || 'Demo User',
      email: updates.email || 'demo@horizonai.com',
      plan: 'free',
      createdAt: new Date('2024-01-01'),
    };
  },

  async updateSettings(_settings: Record<string, unknown>): Promise<void> {
    await simulateDelay(300);
  },
};

// ============ FAQ Service ============
export const faqService = {
  async getFAQs(): Promise<{ question: string; answer: string }[]> {
    await simulateDelay(200);
    return faqData;
  },
};

// ============ Suggested Prompts Service ============
export const promptsService = {
  async getSuggestedPrompts(): Promise<typeof suggestedPrompts> {
    await simulateDelay(200);
    return suggestedPrompts;
  },
};
