import { useState, useEffect, useRef } from 'react';
import { Sidebar } from '../components/chat/Sidebar';
import { ChatInput } from '../components/chat/ChatInput';
import { ChatMessage } from '../components/chat/ChatMessage';
import { ModelSelector } from '../components/chat/ModelSelector';
import { Button } from '../components/ui/Button';
import { Modal } from '../components/ui/Modal';
import { mockConversations, suggestedPrompts } from '../data/mockData';
import type { Conversation, Message } from '../types';
import { generateId } from '../utils/helpers';
import {
  Menu,
  Plus,
  Sparkles,
  PanelLeft,
  PanelLeftClose,
} from 'lucide-react';

interface ChatPageProps {
  onNavigate: (path: string) => void;
}

export function ChatPage({ onNavigate }: ChatPageProps) {
  const [conversations, setConversations] = useState<Conversation[]>(mockConversations);
  const [activeConversation, setActiveConversation] = useState<string | null>(null);
  const [selectedModel, setSelectedModel] = useState('horizon-auto');
  const [isGenerating, setIsGenerating] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [showUpgradeModal, setShowUpgradeModal] = useState(false);
  const [userPlan] = useState<'free' | 'premium1' | 'premium2'>('free');
  
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const activeConv = conversations.find(c => c.id === activeConversation);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [activeConv?.messages]);

  const handleNewChat = () => {
    const newConv: Conversation = {
      id: generateId(),
      title: 'New conversation',
      messages: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    };
    setConversations([newConv, ...conversations]);
    setActiveConversation(newConv.id);
  };

  const handleSendMessage = async (content: string) => {
    if (!activeConversation) {
      // Create new conversation
      const newConv: Conversation = {
        id: generateId(),
        title: content.slice(0, 30) + (content.length > 30 ? '...' : ''),
        messages: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      };
      setConversations([newConv, ...conversations]);
      setActiveConversation(newConv.id);
      
      // Add user message
      const userMessage: Message = {
        id: generateId(),
        role: 'user',
        content,
        timestamp: new Date(),
      };
      
      // Simulate AI response
      setIsGenerating(true);
      setTimeout(() => {
        const aiMessage: Message = {
          id: generateId(),
          role: 'assistant',
          content: `This is a demo response from ${selectedModel}. In production, this would be generated by the actual AI model.\n\nYou asked: "${content}"\n\n## What happens next?\n\nWhen the backend is connected:\n1. Your message will be sent to the AI API\n2. The selected model will generate a response\n3. The response will stream back in real-time\n4. You can continue the conversation naturally`,
          timestamp: new Date(),
          model: selectedModel,
        };
        
        setConversations(prev => prev.map(c => 
          c.id === newConv.id 
            ? { ...c, messages: [userMessage, aiMessage], updatedAt: new Date() }
            : c
        ));
        setIsGenerating(false);
      }, 1500);
      
      return;
    }

    // Add user message to existing conversation
    const userMessage: Message = {
      id: generateId(),
      role: 'user',
      content,
      timestamp: new Date(),
    };

    setConversations(prev => prev.map(c =>
      c.id === activeConversation
        ? {
            ...c,
            messages: [...c.messages, userMessage],
            title: c.messages.length === 0 ? content.slice(0, 30) + '...' : c.title,
            updatedAt: new Date(),
          }
        : c
    ));

    // Simulate AI response
    setIsGenerating(true);
    setTimeout(() => {
      const aiMessage: Message = {
        id: generateId(),
        role: 'assistant',
        content: `This is a demo response. In production, this would be a real AI-generated response.\n\nYour message: "${content}"\n\n### Features that will be available:\n\n- **Real AI responses** from the selected model\n- **Streaming output** for faster perceived response time\n- **Code syntax highlighting** for code blocks\n- **Follow-up questions** and conversation memory\n- **Multi-model support** for complex tasks`,
        timestamp: new Date(),
        model: selectedModel,
      };

      setConversations(prev => prev.map(c =>
        c.id === activeConversation
          ? { ...c, messages: [...c.messages, userMessage, aiMessage], updatedAt: new Date() }
          : c
      ));
      setIsGenerating(false);
    }, 1500);
  };

  const handleDeleteConversation = (id: string) => {
    setConversations(prev => prev.filter(c => c.id !== id));
    if (activeConversation === id) {
      setActiveConversation(null);
    }
  };

  const handleToggleFavorite = (id: string) => {
    setConversations(prev => prev.map(c =>
      c.id === id ? { ...c, isFavorite: !c.isFavorite } : c
    ));
  };

  const handleStopGeneration = () => {
    setIsGenerating(false);
  };

  return (
    <div className="min-h-screen bg-bg-primary flex">
      {/* Sidebar */}
      <Sidebar
        conversations={conversations}
        activeConversation={activeConversation || undefined}
        onSelectConversation={setActiveConversation}
        onNewChat={handleNewChat}
        onDeleteConversation={handleDeleteConversation}
        onToggleFavorite={handleToggleFavorite}
        userPlan={userPlan}
        onNavigate={onNavigate}
        isOpen={sidebarOpen}
        onClose={() => setSidebarOpen(false)}
      />

      {/* Main Content */}
      <div className="flex-1 flex flex-col min-h-screen">
        {/* Top Bar */}
        <header className="flex items-center justify-between px-4 py-3 border-b border-border-default bg-bg-primary/80 backdrop-blur">
          <div className="flex items-center gap-3">
            <button
              onClick={() => setSidebarOpen(!sidebarOpen)}
              className="p-2 rounded-lg hover:bg-slate-800 text-slate-400 lg:hidden"
            >
              <Menu className="w-5 h-5" />
            </button>
            <button
              onClick={() => setSidebarOpen(!sidebarOpen)}
              className="hidden lg:flex p-2 rounded-lg hover:bg-slate-800 text-slate-400"
            >
              {sidebarOpen ? (
                <PanelLeftClose className="w-5 h-5" />
              ) : (
                <PanelLeft className="w-5 h-5" />
              )}
            </button>
            <ModelSelector
              selectedModel={selectedModel}
              onSelectModel={setSelectedModel}
              userPlan={userPlan}
              onUpgradeClick={() => setShowUpgradeModal(true)}
            />
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={handleNewChat}
            leftIcon={<Plus className="w-4 h-4" />}
          >
            New Chat
          </Button>
        </header>

        {/* Chat Area */}
        <main className="flex-1 overflow-y-auto">
          {activeConv && activeConv.messages.length > 0 ? (
            <div className="max-w-3xl mx-auto px-4 py-8">
              {activeConv.messages.map((message) => (
                <ChatMessage
                  key={message.id}
                  message={message}
                  onRegenerate={() => console.log('Regenerate')}
                  onFeedback={(feedback) => console.log('Feedback:', feedback)}
                />
              ))}
              {isGenerating && (
                <div className="py-4">
                  <div className="flex items-center gap-2 text-slate-400">
                    <div className="flex gap-1">
                      <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                      <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                      <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                    </div>
                    <span>AI is thinking...</span>
                  </div>
                </div>
              )}
              <div ref={messagesEndRef} />
            </div>
          ) : (
            /* Empty State */
            <div className="h-full flex flex-col items-center justify-center px-4">
              <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center mb-6">
                <Sparkles className="w-10 h-10 text-white" />
              </div>
              <h2 className="text-2xl font-bold text-slate-100 mb-2">
                How can I help you today?
              </h2>
              <p className="text-slate-400 mb-8">
                Ask anything or choose a suggestion below
              </p>
              <div className="grid sm:grid-cols-2 gap-3 max-w-2xl w-full">
                {suggestedPrompts.map((prompt, index) => (
                  <button
                    key={index}
                    onClick={() => handleSendMessage(prompt.prompt)}
                    className="p-4 rounded-xl border border-border-default bg-bg-card hover:border-indigo-500/50 transition-colors text-left"
                  >
                    <div className="text-2xl mb-2">{prompt.icon}</div>
                    <div className="font-medium text-slate-200">{prompt.title}</div>
                    <div className="text-sm text-slate-500 truncate">{prompt.prompt}</div>
                  </button>
                ))}
              </div>
            </div>
          )}
        </main>

        {/* Input Area */}
        <footer className="border-t border-border-default p-4 bg-bg-primary">
          <ChatInput
            onSend={handleSendMessage}
            isLoading={isGenerating}
            onStop={handleStopGeneration}
            isGenerating={isGenerating}
          />
        </footer>
      </div>

      {/* Upgrade Modal */}
      <Modal
        isOpen={showUpgradeModal}
        onClose={() => setShowUpgradeModal(false)}
        title="Unlock Premium Features"
        size="md"
      >
        <div className="text-center">
          <div className="w-16 h-16 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center mx-auto mb-4">
            <Sparkles className="w-8 h-8 text-white" />
          </div>
          <h3 className="text-xl font-semibold text-slate-100 mb-2">
            Upgrade to access this model
          </h3>
          <p className="text-slate-400 mb-6">
            Premium models offer advanced capabilities for complex tasks, coding, and creative work.
          </p>
          <div className="flex flex-col gap-3">
            <Button
              variant="primary"
              fullWidth
              onClick={() => {
                setShowUpgradeModal(false);
                onNavigate('/pricing');
              }}
            >
              View Plans
            </Button>
            <Button
              variant="ghost"
              fullWidth
              onClick={() => setShowUpgradeModal(false)}
            >
              Maybe Later
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
}
